### PR TITLE
feat: update vscode UI toolkit to fast v2

### LINKED ISSUE #193: Component Icon Spacing Is Not Rendering Correctly Inside VS Code
### Describe the bug

The spacing of icons inside some components is not being rendered correctly when compared to its Storybook counterpart.

### To reproduce

The easiest way to reproduce is:

- Open the all-components [sample extension](https://github.com/microsoft/vscode-webview-ui-toolkit-samples)

### Expected behavior

All components that render icons should look identical to their counterpart in Storybook.

### Screenshots

Screen Shot 2021-08-31 at 10 21 55 PM
Screen Shot 2021-08-31 at 10 22 04 PM

### Desktop (please complete the following information):

-   OS Version: `macOS 11.5.2`
-   Toolkit Version: `v0.6.1`

### LINKED ISSUE #261: Convert Toolkit to Use FAST Foundation v2
### Feature/component description

Rewrite the toolkit to adopt `fast-foundation` v2 and its new API.

### Use case

This is a prerequisite to a number of planned changes and component additions for the toolkit.

### PR DESCRIPTION
**Pull request by chrisdholt**
## Link to relevant issue

This pull request resolves #261
This pull request resolves #193 

## Description of changes

This PR updates the VSCode Webview UI Toolkit to leverage FAST Foundation v2. In FAST Foundation v2 there are a number of improvements which add additional ergonomics and support to component libraries and design systems. The following details provide insight into the changes.

### Foundation Element
One of the most significant changes for FAST Foundation v2 is the added support of FoundationElement and `Configuration` which provides a method of registration and additional configuration abilities by consumers of _design systems and/or component libraries_ such as this. 

##### Templates and styles are functions
One part of this change is that templates and therefore styles in `@microsoft/fast-foundation` are now _functions_ with arguments for a context and definition object. 

##### Context
While not a robust accounting of all features available, it may be helpful to know that context enables the easy nesting of components while still enabling the configuration of unique (dynamic) prefixes), providing greater extensibility. This allows FAST (and other DS authors such as vscode) to _nest_ components without needing to know the finale web component prefix. Consider the below template and styles:

```ts
const myFancyTemplate = (context, definition) => html`
    <template id="elementRoot">
         <slot></slot>
         <${context.tagFor(Button)}>${x => x.buttonText}</${context.tagFor(Button)}>
    </template>
```

```ts
const myFancyStyles = (context, definition) => css`
    :host {
        display: block;
    }
    
    ${context.tagFor(Button)} {
        // my nested button styles
    }
`;
```

When registered by default, the output above will be:

```html
<my-fancy-element id="elementRoot">
     <slot></slot>
    <vscode-button>Button Text</vscode-button>
</my-fancy-element>
```

```css
    :host {
        display: block;
    }
    
    vscode-button {
        // my nested button styles
    }
```

Given a different prefix at registration time, such as `foo`, the button element and it's declaration in the styles file would reference `foo-button`.

#### Definition
Definition provides another layer of customization at configuration time. Currently at the Fast Foundation level, the primary use of `definition` is to enumerate slots which should support "default slotted content". Rather than relying on slotted content to be baked into the `fast-foundation` templates, libraries now define the default slotted content during composition. Additionally, users of these libraries/design systems are now able to _register_ the elements with their own instance of default slotted content. Scenarios here may be the desire to swap out the default SVG for dropdown or to include a different SVG for the checkbox `checked` indicator.

#### Registration
Previously, the default export _was_ elements themselves and you would need to import and reference them to prevent tree shaking and ensure that they were available for use. Now, the export here is a _registration_ for the element which enables its use. 

More details on registration and configuration can be found here: https://www.fast.design/docs/design-systems/fast-frame#create-a-designsystem

Registration provides an opportunity to add global configurations across an application. Consider a scenario where (for some reason), an extension author needs to run the shadow DOM in `closed` mode - this, as well as template replacement, style changes, updates to default slotted content, etc...are all enable. Find out more about configuration during registration here: https://www.fast.design/docs/design-systems/fast-frame/#configuring-components-during-registration

As always, CSS can be used to target elements globally, slotted content will project and replace any default slotted content, and everything else about HTML elements continue to work as expected.

Again, this isn't exhaustive, but hopefully this provides context for some clear deltas between v1 and v2.

## Link to forked docs site

TBD...

_Please see `CONTRIBUTING.md` for directions on how this can be done._

### CODE REVIEW

**Comment by chrisdholt** [comment]
@hawkticehurst I'll look into the build failure. _Something_ is not working with eslint. I'm going to look into that. As I mentioned previously I think, the `eslint` errors shouldn't exist. Something odd is definitely going on here. I have a no-unused-vars error for all the types I've added _and used_ :).

**Comment by chrisdholt** [comment]
> @hawkticehurst I'll look into the build failure. _Something_ is not working with eslint. I'm going to look into that. As I mentioned previously I think, the `eslint` errors shouldn't exist. Something odd is definitely going on here. I have a no-unused-vars error for all the types I've added _and used_ :).

eslint resolved - significant version mismatch between that used by the current FAST eslint rules and the repo. I've resolved to a similar version for now. We've had an rfc out (https://github.com/microsoft/fast/issues/4468) for improving the rules and that would likely include changes to the versions; we can likely prioritize that. Seems like there's been some good improvements to eslint :).

The build is related to a type issue that _shouldn't_ be present, so I'll look into that.

**Comment by chrisdholt** [comment]
> > @hawkticehurst I'll look into the build failure. _Something_ is not working with eslint. I'm going to look into that. As I mentioned previously I think, the `eslint` errors shouldn't exist. Something odd is definitely going on here. I have a no-unused-vars error for all the types I've added _and used_ :).
> 
> eslint resolved - significant version mismatch between that used by the current FAST eslint rules and the repo. I've resolved to a similar version for now. We've had an rfc out ([microsoft/fast#4468](https://github.com/microsoft/fast/issues/4468)) for improving the rules and that would likely include changes to the versions; we can likely prioritize that. Seems like there's been some good improvements to eslint :).
> 
> The build is related to a type issue that _shouldn't_ be present, so I'll look into that.

Build resolved!

The issue the build was hitting was due to a type conflict for the compose function and its override function. We're tracking an issue for the error, but I was surprised to seeing it error in this context. The delta here is that there is the default definition for Foundation and an Override definition. In one of those, a type can be undefined so there is a mismatch. We just need to do some type work.

To accommodate the issue, instead of dropping ALL currently enabled strict modes, I just turned this instance off.

**Comment by hawkticehurst** [comment]
@chrisdholt Cloned your PR locally to do some testing and looks like there are a couple of issues.

**Storybook**

- Data grid component not rendering
- Dropdown stories have an error
- Panels stories have an error

**[All Components Sample](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/all-components)**

_Note: We currently use the all-components sample extension to test the toolkit inside a real VS Code environment (we've found there are times when Storybook and Webviews have discrepancies in rendering)._

_We have future plans of creating a proper automated testing pipeline, but for now, we just have to manually build the toolkit `dist` directory and then copy/paste/replace it with `node_modules/@vscode/webview-ui-toolkit/dist` inside the all-components sample._

- Data grid component not rendering
- Dropdown and panel components seem to be fine!

**Comment by hawkticehurst** [comment]
> Got these resolved - a couple of type issues and then the Data Grid issue was related to needing to provide a mapping to register the base class. Should be all good!

Yay! Thank you so much! 

I'll validate the changes, do a final PR review, and assuming all looks good I'm ready to approve and merge!

**Comment by chrisdholt** [comment]
> @chrisdholt Looks like there are still issues with the data grid in the sample extension.
> 
> Screen Shot 2021-10-21 at 2 35 46 PM
> 
> Did this update change how the data grid should be instantiated?
> 
> Currently, the default data grid is created with the following code in the sample extension.
> 
> ```
> <vscode-data-grid id="default-grid" grid-template-columns="1fr 1fr 1fr 1fr" aria-label="Default"></vscode-data-grid>
> ```
> 
> ```js
> const defaultDataGrid = document.getElementById("default-grid");
>   defaultDataGrid.rowsData = [
>     {
>       column1: "Cell Data",
>       column2: "Cell Data",
>       column3: "Cell Data",
>       column4: "Cell Data",
>     },
>     {
>       column1: "Cell Data",
>       column2: "Cell Data",
>       column3: "Cell Data",
>       column4: "Cell Data",
>     },
>     {
>       column1: "Cell Data",
>       column2: "Cell Data",
>       column3: "Cell Data",
>       column4: "Cell Data",
>     },
>   ];
> ```

How can I run/test this on my end? I believe what I've added should've addressed this, but would be good to know if I can run locally.

**Pull request merged**
